### PR TITLE
Rspec and Rubocop gems + configuration

### PR DESCRIPTION
**Pull request by jonmast**
Add and configure the rspec and rubocop gems. I copied the rubocop.yml file from our chess project, if anyone would like to change any of those settings they are open for discussion.

### CODE REVIEW

**Comment by radiofreemattd** [comment]
All looks standard to me 👍

**Comment by Mikeysax** [comment]
I think you should add factory girl to this and capybara, and it should be good.

**Comment by jonmast** [comment]
I don't think capybara will be helpful here, it is for full-stack apps not APIs. FactoryGirl is a good idea though, I'll add that.

**Comment by Mikeysax** [comment]
Yeah I wrote it and realized how much that didn't make sense hah.

**Comment by Mikeysax** [comment]
:+1:

**Comment by dino217** [comment]
:+1:

**Comment by radiofreemattd** [comment]
Looks good. Thumbs up and merging...

**Comment by MrMonsk** [comment]
Can someone explain to me the reason why rubocop has max linelength of 120 in this case?

Otherwise everything looks good to me! :)

**Pull request merged**
